### ISSUE TITLE
[CCL] Homepage: Jump to council, by postcode

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#182]
- [ ] Same search input as #181, at the top of the homepage(s) (@zarino)
- [ ] Same disambiguation behaviour as the header search input in #177, for postcodes covered by more than one authority (@zarino)
- [ ] Picking a council switches to the correct homepage, and jumps you down to the council’s matching row in the table, highlighting the table row, just like #181 (@zarino)

**Comment by zarino** [comment]
We decided not to do this.
